export const LEGO = [
    {
        name: 'Castaway\'s Raft',
        sn: '6257',
        url: 'https://zklockow.pl/lego-43230-disney-kamera-walta-disneya',
        img: 'https://zklockow.pl/img/640/lego-disney-43230-kamera-walta-disneya-1.jpg',
        owned: true, 
        year: 1989,     
    },
    {
        name: 'Hook and Haul Wrecker',
        sn: '6660',
        url: 'https://zklockow.pl/lego-43230-disney-kamera-walta-disneya',
        img: 'https://zklockow.pl/img/640/lego-disney-43230-kamera-walta-disneya-1.jpg',
        owned: true,   
        year: 1989,   
    },
    {
        name: 'Rescue Helicopter',
        sn: '6482',
        url: 'https://zklockow.pl/lego-43230-disney-kamera-walta-disneya',
        img: 'https://zklockow.pl/img/640/lego-disney-43230-kamera-walta-disneya-1.jpg',
        owned: true, 
        year: 1989,     
    },
    {
        name: 'Light and Sound Construction Crew',
        sn: '6481',
        url: 'https://zklockow.pl/lego-43230-disney-kamera-walta-disneya',
        img: 'https://zklockow.pl/img/640/lego-disney-43230-kamera-walta-disneya-1.jpg',
        owned: true,   
        year: 1989,   
    },
    {
        name: 'Auxiliary Patroller',
        sn: '6850',
        url: 'https://zklockow.pl/lego-43230-disney-kamera-walta-disneya',
        img: 'https://zklockow.pl/img/640/lego-disney-43230-kamera-walta-disneya-1.jpg',
        owned: true,   
        year: 1989,   
    },
    {
        name: 'King\'s Mountain Fortress',
        sn: '6081',
        url: 'https://zklockow.pl/lego-43230-disney-kamera-walta-disneya',
        img: 'https://zklockow.pl/img/640/lego-disney-43230-kamera-walta-disneya-1.jpg',
        owned: true,   
        year: 1990,   
    },

    {
        name: 'Particle Ionizer',
        sn: '6923',
        url: 'https://zklockow.pl/lego-43230-disney-kamera-walta-disneya',
        img: 'https://zklockow.pl/img/640/lego-disney-43230-kamera-walta-disneya-1.jpg',
        owned: true,   
        year: 1990,   
    },
    {
        name: 'Beacon Tracer',
        sn: '6833',
        url: 'https://zklockow.pl/lego-43230-disney-kamera-walta-disneya',
        img: 'https://zklockow.pl/img/640/lego-disney-43230-kamera-walta-disneya-1.jpg',
        owned: true,   
        year: 1990,   
    },
    {
        name: 'Safari Off Road Vehicle',
        sn: '6672',
        url: 'https://zklockow.pl/lego-43230-disney-kamera-walta-disneya',
        img: 'https://zklockow.pl/img/640/lego-disney-43230-kamera-walta-disneya-1.jpg',
        owned: true,   
        year: 1990,   
    },
    {
        name: 'Coastal Cutter',
        sn: '6353',
        url: 'https://zklockow.pl/lego-43230-disney-kamera-walta-disneya',
        img: 'https://zklockow.pl/img/640/lego-disney-43230-kamera-walta-disneya-1.jpg',
        owned: true,   
        year: 1990,   
    },
    {
        name: 'Diesel Dumper',
        sn: '6532',
        url: 'https://zklockow.pl/lego-43230-disney-kamera-walta-disneya',
        img: 'https://zklockow.pl/img/640/lego-disney-43230-kamera-walta-disneya-1.jpg',
        owned: true,   
        year: 1991,   
    },
    {
        name: 'Beach Bandit',
        sn: '6534',
        url: 'https://zklockow.pl/lego-43230-disney-kamera-walta-disneya',
        img: 'https://zklockow.pl/img/640/lego-disney-43230-kamera-walta-disneya-1.jpg',
        owned: true,   
        year: 1992,   
    },
    {
        name: 'Ice Tunnelator',
        sn: '6814',
        url: 'https://zklockow.pl/lego-43230-disney-kamera-walta-disneya',
        img: 'https://zklockow.pl/img/640/lego-disney-43230-kamera-walta-disneya-1.jpg',
        owned: true,   
        year: 1993,   
    },
    {
        name: 'Space Minifigures',
        sn: '6703',
        url: 'https://zklockow.pl/lego-43230-disney-kamera-walta-disneya',
        img: 'https://zklockow.pl/img/640/lego-disney-43230-kamera-walta-disneya-1.jpg',
        owned: true,   
        year: 1988,   
    },
    {
        name: 'Castle Minifigures',
        sn: '6103-1',
        url: 'https://zklockow.pl/lego-43230-disney-kamera-walta-disneya',
        img: 'https://zklockow.pl/img/640/lego-disney-43230-kamera-walta-disneya-1.jpg',
        owned: true,   
        year: 1988,   
    },
    {
        name: 'Road Rebel',
        sn: '6644',
        url: 'https://zklockow.pl/lego-43230-disney-kamera-walta-disneya',
        img: 'https://zklockow.pl/img/640/lego-disney-43230-kamera-walta-disneya-1.jpg',
        owned: true,   
        year: 1990,   
    },
]

